### ISSUE TITLE
DE locale restrictions are not applied for Chrome browser

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#1998]
[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- German language was added in Chrome browser from "Settings > Advanced settings > Language and input settings..." (in top of the list).

[Steps to reproduce]:
1. Open Chrome browser and navigate to https://testpilot.stage.mozaws.net page.
2. Scroll down on the page and observe the available experiments for German localization.

[Expected result]:
- Only Page Shot, Min Vid and Tab Center experiments are displayed for DE language.

[Actual result]:
- All available experiments are displayed for DE language.

![all experiments chrome](https://cloud.githubusercontent.com/assets/17258026/21768592/085b9312-d683-11e6-8964-c4a27c8ceee6.png)

**Comment by johngruen** [comment]
@chuckharmston, hmm, well this doesn't block shipping cliqz i don't think, but we should resolve this. Not sure how you flagged languages, but maybe we should audit for cross browser compatibility.

**Comment by jaredhirsch** [comment]
@SoftVision-PaulOiegas pinged me on IRC to add that this was for the de-de locale

**Comment by ghost** [comment]
This may be fixed with the de/de-de fix from a while ago

**Comment by SoftVision-PaulOiegas** [comment]
Nope, still reproducing on Chrome. Just tested with German and German (Germany). I assume first is the simple [de] and second is [de-de].

**Comment by johngruen** [comment]
@fzzzy adding locales to URLs may resolve this

**Comment by SoftVision-PaulOiegas** [comment]
Just an addition, Cliqz experiment is not even displayed on Chrome if any German language (de, de-de, de-at, de-ch, etc) is set as content language.

**Comment by ForsakenHarmony** [comment]
Why is the page displayed in german, even though I have my main language set to english? what's up with the shitty language detection everywhere

**Comment by fzzzy** [comment]
@ForsakenHarmony It's a bug. We hope to have it fixed on Tuesday.

**Comment by chuckharmston** [comment]
Closing since Cliqz is retiring tomorrow. We can reopen if we ever have language-restricted experiments.
