### ISSUE TITLE
Twitter Images aren't working for new experiments

### ISSUE THREAD

**Issue by johngruen** [mozilla/testpilot#2244]
## expected
tweeting an experiment link shows an image

## actual
<img width="570" alt="screen shot 2017-02-27 at 2 38 26 pm" src="https://cloud.githubusercontent.com/assets/3323249/23376569/9652823c-fcfa-11e6-93ba-44614782df77.png">

**Comment by lmorchard** [comment]
Hmm, this seems to be happening for other older experiments, too, if you [check the Twitter card validator](https://cards-dev.twitter.com/validator). Did we change something with this recently?
<img width="618" alt="screenshot 2017-02-27 14 52 00" src="https://cloud.githubusercontent.com/assets/21687/23377030/58238b94-fcfc-11e6-85cb-9cb9f2a4c1a3.png">

**Comment by lmorchard** [comment]
Looks like [the code in the template for `twitter:image` is 5 months old](https://github.com/mozilla/testpilot/blame/master/frontend/src/templates/index.mustache#L25) and [the code generating those pages is old too](https://github.com/mozilla/testpilot/blame/master/frontend/tasks/pages.js#L51). I'd say maybe we need to append `https://testpilot.firefox.com` onto all those URLs, but if that fixes it I wonder why it's worked at all until now

**Comment by pdehaan** [comment]
... It looks like it's defaulting to a fallback social image [in the HTML]:

```html
<head>
  <link rel="canonical" href="https://testpilot.firefox.com/">
  ...
  <title data-l10n-id="pageTitleExperiment" data-l10n-args="...">Firefox Test Pilot - ⁨Pulse⁩</title>
  <meta property="og:title" content="Firefox Test Pilot">
  <meta name="twitter:title" content="Firefox Test Pilot">
  <meta name="description" content="Test new Features. Give us feedback. Help build Firefox.">
  <meta property="og:description" content="Test new Features. Give us feedback. Help build Firefox.">
  <meta name="twitter:description" content="Test new Features. Give us feedback. Help build Firefox.">
  <meta name="twitter:card" content="summary">
  <meta property="og:image" content="https://testpilot.firefox.com/static/images/thumbnail-facebook.png">
  <meta name="twitter:image" content="https://testpilot.firefox.com/static/images/thumbnail-twitter.png">
</head>
```

Expected: [/content-src/experiments/pulse.yaml:18-19](https://github.com/mozilla/testpilot/blob/2af8327d6e0497911107589a8cac43edbb6ba8ae/content-src/experiments/pulse.yaml#L18-L19):

```yaml
image_twitter: /static/images/experiments/pulse/social/pulse-twitter.jpg
image_facebook: /static/images/experiments/pulse/social/pulse-facebook.jpg
```

**Comment by lmorchard** [comment]
> It looks like it's defaulting to a fallback social image

Did you directly navigate to that experiment page? Or did you click through to it from the front page? If the former, that's a bug. But, if it's the latter, you're seeing the HTML for the front page loaded from the server and then React router takes over (and does not update the header HTML)

Try refreshing and see if you see the correct tags. A direct load of the experiment URL should bring up the same HTML that the social media spiders see

**Comment by johngruen** [comment]
@pdehaan @lmorchard not sure if this matters but, 

https://testpilot.firefox.com/static/images/experiments/cliqz/icon/thumbnail.png (or similar) redirect to our 404 whereas https://testpilot.firefox.com/static/images/thumbnail-twitter.png goes to the asset

**Comment by pdehaan** [comment]
Yeah, looks like navigating directly to the page gives me the right `<meta>` tags, whereas browsing the site and related experiments always gives me incorrect/stale content.
Refreshing the page (after browsing) then brings up the correct content. 👎 

**UPDATE:** Of course, this seems semi-unrelated to the core issue of Twitter not displaying the correct information when pasting the URL into a tweet, which is different from the nonsense I'm saying above. I'll shut up now.

**Comment by johngruen** [comment]
@pdehaan presumably that wouldn't be at issue with the embed not showing since Twitter would not be navigating directly. Also, wrt my previous comment, it looks like there's some cache busting on the experiment images in dist so the URLs are more like this: https://testpilot.firefox.com//static/images/experiments/snooze-tabs/social/snooze-tabs-twitter.feb8b7d6.jpg

I have a PR that will fix this (i think).

**Comment by johngruen** [comment]
@pdehaan so that doesn't fix the stale content issue (which may not be an issue since FB and Twit will always look at the page directly) but AFAICT the path to the image needs to be absolute for it to render in Twitter.

**Comment by lmorchard** [comment]
> Yeah, looks like navigating directly to the page gives me the right `<meta>` tags, whereas browsing the site and related experiments always gives me incorrect/stale content.
Refreshing the page (after browsing) then brings up the correct content. 👎 

Yeah, like I said: That's how this single-page-app thing works with React Router. Once you've loaded that HTML from the front page with generic meta tags, we don't bother updating that part of the DOM for experiments because it's not visible or useful in the app itself. You have to directly load those URLs from the server to get the meta tags - which is what the spiders do.

**Comment by lmorchard** [comment]
Hmm, seems like this #2247 didn't fix things. 😞 [Now the Twitter image is 404](https://testpilot.firefox.com/static/images/experiments/snooze-tabs/social/snooze-tabs-twitter.jpg), because rev-all [renamed the image filename with a hash](https://s3.amazonaws.com/testpilot.dev.mozaws.net/static/images/experiments/snooze-tabs/social/snooze-tabs-twitter.feb8b7d6.jpg) and [the absolute URL didn't pick that up](https://testpilot.firefox.com/static/images/experiments/snooze-tabs/social/snooze-tabs-twitter.jpg). Probably need to add another exception to make rev-all skip those images

**Comment by lmorchard** [comment]
I think the PR I just submitted should fix the 404

**Comment by ghost** [comment]
PR number?  and/or did it fix this?

**Comment by lmorchard** [comment]
> PR number? and/or did it fix this?

#2251, should be listed above my comment. Haven't had a chance to verify whether it fixed this though. Edit: Might not be, since that was merged but this is still a 404 - https://testpilot.dev.mozaws.net/static/images/experiments/snooze-tabs/social/snooze-tabs-facebook.jpg

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and it still reproducible on dev, stage and production servers for all experiments.
I have also tested this on Facebook and the experiments images are correctly displayed.

Here is a screen shot with the issue:
![twitter](https://cloud.githubusercontent.com/assets/19226534/23855464/6bdf9094-07fe-11e7-8edd-d031dbd5f5ee.png)

**Comment by lmorchard** [comment]
FWIW, this won't work probably until pushed to production: The absolute URLs for images are hardcoded to production, so sharing from dev will link to images that haven't been uploaded to production yet. It'll also never work on dev or stage, unless we vary the build for those servers to change the absolute URL - something that might not be worth doing

**Comment by SoftVision-CosminMuntean** [comment]
Thanks for clarifying this. 
I will retest this issue when the fix will be pushed to production. If it will not reproduce I will closed this issue as fixed.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue and is still reproducible on production.
It seems that now on dev and stage servers the images are correctly displayed. 

Here is a screenshot with the results:
![page-shot-2017-3-16 test testcosmin twitter](https://cloud.githubusercontent.com/assets/19226534/23995074/9a7df450-0a50-11e7-88a5-7ef6e4e20143.png)

**Comment by lmorchard** [comment]
I suspect this might be caching on Twitter's end with respect to prod. If the images are working on dev or stage, they should eventually work on prod - because dev & stage use prod URLs for those images. I just tried the Twitter card validator and prod worked for me:

<img width="1253" alt="screenshot 2017-03-16 12 28 59" src="https://cloud.githubusercontent.com/assets/21687/24007232/54e089f0-0a44-11e7-91ef-a00998ad0d16.png">

**Comment by johngruen** [comment]
For some reason only Pulse is not currently working. URL is fine though. I'll check in a day or two to see what's up

**Comment by lmorchard** [comment]
Hmm, Pulse is working for me in the validator too:

<img width="1746" alt="screenshot 2017-03-20 12 27 29" src="https://cloud.githubusercontent.com/assets/21687/24109987/a58981d2-0d68-11e7-8fc7-5f9d6ed11405.png">

One of the weird dependencies here is we're tied to Twitter's scraper caching, over which I don't think we have any control. (They actually fetch & re-host our images from their own CDN)

**Comment by johngruen** [comment]
@lmorchard yeah i think everything's fine on our end, maybe just caching on Twitter's end...?

**Comment by johngruen** [comment]
Looks like this is good now
