### ISSUE TITLE
Old Firefox logo is still displayed on the Test Pilot and experiments feedback survey

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [mozilla/testpilot#3047]
**[Affected versions]:**
- Firefox 56.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Following 5 prefs have been set or added on a new profile: "extensions.legacy.enabled = true" "xpinstall.signatures.required = false" "testpilot.env = dev" "extensions.webapi.testing = true" "extensions.install.requireBuiltInCerts = false".

**[Steps to reproduce]:**
1. Open Firefox browser and navigate to https://testpilot.dev.mozaws.net page.
2. Scroll down to the page bottom and click the "Give Feedback" button from footer.
3. After redirected to survey page, observe the Firefox logo on top.

**[Expected result]:**
- The new Firefox logo is correctly displayed above the survey form.

**[Actual result]:**
- The old Firefox logo is still displayed above the survey form.

**[Notes]:**
- The old Firefox logo is also displayed for experiments feedback surveys.

![survey logo](https://user-images.githubusercontent.com/17258026/32613059-832b5eb8-c572-11e7-89f7-747795a6d767.png)

**Comment by johngruen** [comment]
This will be a pain to fix since it will require manually updating each survey. I'll simply fix our survey template so that future surveys are not affected.

**Comment by johngruen** [comment]
Fixed this

**Comment by SoftVision-PaulOiegas** [comment]
Not so fast! 😆 Indeed the experiments feedback pages are displaying the new logo and background, but the Test Pilot feedback form still has the old ones displayed.
This one can be accessed from footer link or from /retire page uninstall modal.

Sorry John. 😢

**Comment by johngruen** [comment]
Okay @SoftVision-PaulOiegas fixed it

**Comment by SoftVision-PaulOiegas** [comment]
> or from /retire page uninstall modal.

@johngruen 😢 Nope, still not ok. The one mentioned above still has the old design. But since this happened, it means that we have 2 different feedback surveys for TxP. The one from footer is a general one, and the one from /retire page is a leaving feedback.

![old survey](https://user-images.githubusercontent.com/17258026/32959609-d2f4d7e0-cbca-11e7-8185-33ee14689d6d.png)

**Comment by johngruen** [comment]
OMG

**Comment by johngruen** [comment]
Fixed

**Comment by SoftVision-PaulOiegas** [comment]
Yep, now it seems to be ok. 👍
