### ISSUE TITLE
Error when signing up to FxA account

### ISSUE THREAD

**Issue by mostlygeek** [mozilla/testpilot#445]
Testing on stage I see: 

![testpilot-scope-issue](https://cloud.githubusercontent.com/assets/83972/13504772/c8e4501e-e12a-11e5-9a72-320ddf1dd520.png)

Talked with @jrgm about this and he said the scope value being sent on the wire is blank `""`. @jrgm could you elaborate more? In [the code](https://github.com/mozilla/testpilot/blob/334d776393425df52564d9f1cad99c2b882ed736/testpilot/users/providers/fxa/provider.py#L23) it looks like testpilot wants to send "profile".

**Comment by jrgm** [comment]
So, the initial request is made with scope profile, but after completing authentication, the front end is requesting authorization with scope `""`.

**Comment by seanmonstar** [comment]
This sounds familiar. If the client isn't `trusted` in the fxa-oauth-server, then it isn't allowed to request the `profile` scope. And I believe there's an issue in the content-server to display a better message when this is the case.

**Comment by mostlygeek** [comment]
@seanmonstar does not trusted mean I got the security / access information wrong?

**Comment by seanmonstar** [comment]
There is a `trusted` boolean in the database of the fxa-oauth-server. I don't recall how that is set. I believe stage has our oauth console, and perhaps it allows picking if it is trusted?

**Comment by jrgm** [comment]
So I don't see where setting trusted was supposed to be how this client was configured (or idea town credentials before it was testpilot). If it's supposed to trusted, the change is simple, but @rfk needs to give that approval.

**Comment by rfk** [comment]
Will this be hosted on a mozilla.com or firefox.com domain?  If so, I'm happy for it to have trusted status.  An alternative fix is to just request the scopes you actually need, e.g. "profile:email profile:display_name".

**Comment by lmorchard** [comment]
> Will this be hosted on a mozilla.com or firefox.com domain? If so, I'm happy for it to have trusted status. An alternative fix is to just request the scopes you actually need, e.g. "profile:email profile:display_name".

@rfk: Ultimately, yes, the production site will be at testpilot.firefox.com. But, so far, this issue is just about the staging server at https://testpilot.stage.mozaws.net/

**Comment by mostlygeek** [comment]
@rfk or @seanmonstar when requesting the whole `profile` scope, what does access does that grant? @lmorchard should review since we should be requesting only the privileges we need.

**Comment by rfk** [comment]
> the whole profile scope, what does access does that grant

Ability to read uid, email address, display name and profile picture, which can be requested individually using the following sub-scopes:  "profile:uid profile:email profile:display_name profile:avatar".

**Comment by mostlygeek** [comment]
@rfk if the scope was changed to `profile:email, profile:display_name, profile:avatar` we wouldn't need to set the `trusted` flag then?

**Comment by lmorchard** [comment]
Well, like I said, ultimately this **will** be a firefox.com site - so it probably _should_ be trusted at that point.

What we're talking about here is just getting a staging server up and running. We can play around with the scope requested in the code, but that sounds like possibly a red herring IMO. Our staging server **shouldn't** be accessing any real sensitive PII in any case, just throwaway accounts for testing

**Comment by mostlygeek** [comment]
@lmorchard I'm +1 with having testpilot a trusted site. Though, I still like only requesting what we need.

@jrgm could you flip testpilot's `trusted` flag in STAGE?

**Comment by jrgm** [comment]
> @jrgm could you flip testpilot's trusted flag in STAGE?

Done.

```
| hex(id)          | name                                     | trusted |
+------------------+------------------------------------------+---------+
| 4636D485F6F0C761 | Test Pilot Stage                         |       1 |
```

**Comment by jrgm** [comment]
Hmm

```
KeyError at /accounts/login/callback/

'uid'

Request Method:     GET
Request URL:    https://testpilot.stage.mozaws.net/accounts/login/callback/?state=Pux2GDPNcrnK&code=959796afcc9777c5f8277edcd907bd5cbec99338c4b3fa590412f2919b129122&action=signin
Django Version:     1.8.4
Exception Type:     KeyError
Exception Value:    

'uid'

Exception Location:     /app/testpilot/users/providers/fxa/provider.py in extract_uid, line 26
Python Executable:  /usr/local/bin/python
Python Version:     3.5.1
Python Path:    

['/app',
 '/usr/local/bin',
 '/usr/local/lib/python35.zip',
 '/usr/local/lib/python3.5',
 '/usr/local/lib/python3.5/plat-linux',
 '/usr/local/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/site-packages',
 '/usr/local/lib/python3.5/site-packages/newrelic-2.52.0.40']

Server time:    Thu, 3 Mar 2016 22:45:00 +0000
```

**Comment by mostlygeek** [comment]
I get the same error. Looking at the info it seems this is the response from FxA in stage: 

```
self    

<testpilot.users.providers.fxa.provider.FirefoxAccountsProvider object at 0x7f73b36f9358>

data    

{'code': 404,
 'errno': 999,
 'error': 'Not Found',
 'message': 'Unspecified error'}
```

So it sent a 404 error messages

**Comment by jrgm** [comment]
Is that a 404 response to a request make by the test pilot server, or in the browser?

**Comment by mostlygeek** [comment]
I switched testpilot.stage.mozaws.net over to production FxA. Still the same issue with the `code:404` I mentioned above:

![testpilot-debug-error](https://cloud.githubusercontent.com/assets/83972/13515142/c30743fc-e163-11e5-9467-8ffb73c80251.png)

**Comment by rfk** [comment]
Is testpilot hitting the right URL to get the profile data?

**Comment by rfk** [comment]
Should be https://profile.accounts.firefox.com/v1/profile in production.

**Comment by mostlygeek** [comment]
Nope. Wrong profile URL. Shall fix.

**Comment by mostlygeek** [comment]
Works now. Thanks @rfk.

**Comment by pdehaan** [comment]
> I switched testpilot.stage.mozaws.net over to production FxA

Wait, do we want **stage** TestPilot using the **prod** FxA stack?
That seems like we're crossing streams and could be risky if somebody accidentally load tests stage or something.

**Comment by mostlygeek** [comment]
There was an email thread and this was @rfk suggested approach.

**Comment by lmorchard** [comment]
I still don't think we should be using **production** FxA for a **staging** server. Production testpilot.firefox.com should be trusted on Production FxA - but not staging, IMO. We're not promising the same security assurances and whatnot for PII on staging as for prod.

It sounded like the better thing was to use FxA [Stable development (production clone)](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Firefox_Accounts/Introduction#Firefox_Accounts_deployments) versus FxA Stage.  We use that for local development, and I was using it in AWS Elastic Beanstalk.

**Comment by lmorchard** [comment]
Still kind of dubious about having a staging server be trusted in prod FxA, but just saw the tail end of the email thread... so, if that's the official advice then  ¯\_(ツ)_/¯ let's go with it
